const CONFIGS={
  delight:'data/delight.json',
  blank:'data/blank.json'
};
const qs=s=>document.querySelector(s); const qsa=s=>[...document.querySelectorAll(s)];
const state={products:[],filter:'all'};
function showToast(msg){const t=qs('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function setInstagram(el){el.href=window.__brand?.instagram||'#'}
function renderCollections(items){qs('#collectionGrid').innerHTML=items.map(c=>`<a class="collection-card" href="#shop" data-jump="${c.filter}"><img src="${c.image}" alt="${c.name}" loading="lazy"><div class="collection-card-content"><span>${c.eyebrow}</span><h3>${c.name}</h3></div></a>`).join('')}
function renderProducts(){const filtered=state.filter==='all'?state.products:state.products.filter(p=>p.category===state.filter);const grid=qs('#productGrid');grid.innerHTML=filtered.map((p,i)=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-info"><div class="product-top"><div class="product-title">${p.name}</div><div class="product-price">${p.price}</div></div><div class="product-label">${p.label}</div><button data-product="${i}">View details →</button></div></article>`).join('');grid.querySelectorAll('[data-product]').forEach((b,i)=>b.addEventListener('click',()=>openProduct(filtered[i])))}
function openProduct(p){const d=qs('#productDialog'),body=qs('#dialogBody');body.innerHTML=`<div class="dialog-media"><img src="${p.image}" alt="${p.name}"></div><div class="dialog-copy"><div class="eyebrow">${p.label}</div><h3>${p.name}</h3><p>${p.desc}</p><strong>${p.price}</strong><div style="margin-top:20px"><a class="button dark" target="_blank" rel="noopener" href="${window.__brand.instagram}">Ask about this piece ↗</a></div></div>`;d.showModal()}
function toggleMenu(open){qs('#mobileNav').classList.toggle('open',open);qs('#scrim').classList.toggle('show',open);qs('#menuBtn').setAttribute('aria-expanded',String(open));qs('#mobileNav').setAttribute('aria-hidden',String(!open));document.body.classList.toggle('menu-open',open)}
function loadClient(){const params=new URLSearchParams(location.search);const client=params.get('client')||'delight';const config=CONFIGS[client]||CONFIGS.delight;fetch(config).then(r=>{if(!r.ok)throw Error('config');return r.json()}).then(c=>render(c)).catch(()=>{if(client!=='delight')fetch(CONFIGS.delight).then(r=>r.json()).then(render);else showToast('Demo loaded with a local fallback.')})}
function render(c){window.__brand=c;document.title=c.brand;document.querySelector('meta[name=description]').content=c.heroText;document.querySelectorAll('[data-brand]').forEach(e=>e.textContent=c.brand);document.querySelector('[data-tagline]').textContent=c.tagline;document.querySelector('[data-location]').textContent=c.location;document.querySelector('[data-hero-title]').textContent=c.heroTitle;document.querySelector('[data-hero-text]').textContent=c.heroText;qs('#heroImage').src=c.heroImage;qs('#heroImage').alt=c.heroTitle;qs('#mobileInstagram').href=c.instagram;qs('#galleryInstagram').href=c.instagram;qs('#contactInstagram').href=c.instagram;qs('#footerInstagram').href=c.instagram;qs('#footerInstagram').textContent=c.handle;renderCollections(c.collections||[]);state.products=c.products||[];renderProducts()}
qsa('.filter').forEach(btn=>btn.addEventListener('click',()=>{qsa('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.filter=btn.dataset.filter;renderProducts()}));
qs('#collectionGrid').addEventListener('click',e=>{const a=e.target.closest('[data-jump]');if(!a)return;e.preventDefault();const f=a.dataset.jump;state.filter=f;qsa('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderProducts();document.querySelector('#shop').scrollIntoView({behavior:'smooth'})});
qs('#menuBtn').addEventListener('click',()=>toggleMenu(true));qs('#closeMenu').addEventListener('click',()=>toggleMenu(false));qs('#scrim').addEventListener('click',()=>toggleMenu(false));qsa('#mobileNav a[href^="#"]').forEach(a=>a.addEventListener('click',()=>toggleMenu(false)));qs('#dialogClose').addEventListener('click',()=>qs('#productDialog').close());
window.addEventListener('offline',()=>qs('#offlineBar').classList.add('show'));window.addEventListener('online',()=>{qs('#offlineBar').classList.remove('show');showToast('Back online.')});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
loadClient();
